name: bharat_verify
description: A verification app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1  # <--- The Icon Tool

# --- ICON CONFIGURATION ---
flutter_icons:
  android: true
  ios: true
  image_path: "logo.png"  # <--- Uses your uploaded image
# --------------------------

flutter:
  uses-material-design: true
