name: best_verifier
description: Best Verifier - Your secure document assistant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The Bridge: Detects and launches official Gov apps (QR Scanner, mAadhaar)
  external_app_launcher: ^4.0.3 
  # Browser: Opens standard web URLs (Incometax, Parivahan)
  url_launcher: ^6.3.0
  # Style: Professional fonts for the UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Icon Generator
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
