name: Build Android App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Recreate Android Project
        run: |
          mkdir temp_safe
          mv lib temp_safe/
          mv assets temp_safe/
          mv pubspec.yaml temp_safe/
          
          flutter create . --org com.innomind.bharatverify --project-name bharat_verify
          
          rm -rf lib assets pubspec.yaml
          mv temp_safe/lib .
          mv temp_safe/assets .
          mv temp_safe/pubspec.yaml .
          rm -rf temp_safe

      - name: Get Dependencies
        run: flutter pub get

      # --- FORCE ICON GENERATION ---
      - name: Generate App Icon
        run: |
          dart run flutter_launcher_icons
          # Run twice to force overwrite
          dart run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bharat-verify-app
          path: build/app/outputs/flutter-apk/app-release.apk
